package com.basdxz.vshade.query.newstuff;

import lombok.*;

import static org.lwjgl.opengl.GL31.*;
import static org.lwjgl.opengl.GL40.*;
import static org.lwjgl.opengl.GL43.*;
import static org.lwjgl.opengl.GL44.*;

/*
    Reference: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetProgramResource.xhtml
 */
@Getter
public enum QueryProgramResource implements IQueryProgramResource {
    NAME_LENGTH(GL_NAME_LENGTH),
    TYPE(GL_TYPE),
    ARRAY_SIZE(GL_ARRAY_SIZE),
    OFFSET(GL_OFFSET),
    BLOCK_INDEX(GL_BLOCK_INDEX),
    ARRAY_STRIDE(GL_ARRAY_STRIDE),
    MATRIX_STRIDE(GL_MATRIX_STRIDE),
    IS_ROW_MAJOR(GL_IS_ROW_MAJOR),
    ATOMIC_COUNTER_BUFFER_INDEX(GL_ATOMIC_COUNTER_BUFFER_INDEX),
    TEXTURE_BUFFER(GL_TEXTURE_BUFFER),
    BUFFER_BINDING(GL_BUFFER_BINDING),
    BUFFER_DATA_SIZE(GL_BUFFER_DATA_SIZE),
    NUM_ACTIVE_VARIABLES(GL_NUM_ACTIVE_VARIABLES),
    ACTIVE_VARIABLES(GL_ACTIVE_VARIABLES),
    REFERENCED_BY_VERTEX_SHADER(GL_REFERENCED_BY_VERTEX_SHADER),
    REFERENCED_BY_TESS_CONTROL_SHADER(GL_REFERENCED_BY_TESS_CONTROL_SHADER),
    REFERENCED_BY_TESS_EVALUATION_SHADER(GL_REFERENCED_BY_TESS_EVALUATION_SHADER),
    REFERENCED_BY_GEOMETRY_SHADER(GL_REFERENCED_BY_GEOMETRY_SHADER),
    REFERENCED_BY_FRAGMENT_SHADER(GL_REFERENCED_BY_FRAGMENT_SHADER),
    REFERENCED_BY_COMPUTE_SHADER(GL_REFERENCED_BY_COMPUTE_SHADER),
    NUM_COMPATIBLE_SUBROUTINES(GL_NUM_COMPATIBLE_SUBROUTINES),
    COMPATIBLE_SUBROUTINES(GL_COMPATIBLE_SUBROUTINES),
    TOP_LEVEL_ARRAY_SIZE(GL_TOP_LEVEL_ARRAY_SIZE),
    TOP_LEVEL_ARRAY_STRIDE(GL_TOP_LEVEL_ARRAY_STRIDE),
    LOCATION(GL_LOCATION),
    LOCATION_INDEX(GL_LOCATION_INDEX),
    IS_PER_PATCH(GL_IS_PER_PATCH),
    LOCATION_COMPONENT(GL_LOCATION_COMPONENT),
    TRANSFORM_FEEDBACK_BUFFER_INDEX(GL_TRANSFORM_FEEDBACK_BUFFER_INDEX),
    TRANSFORM_FEEDBACK_BUFFER_STRIDE(GL_TRANSFORM_FEEDBACK_BUFFER_STRIDE);

    private final int programResourceType;

    QueryProgramResource(int programResourceType) {
        this.programResourceType = programResourceType;
    }
}
