package com.basdxz.vshade.query.newstuff;

import com.basdxz.vbuffers.common.MemUtils;
import lombok.*;

import java.nio.IntBuffer;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static com.basdxz.vshade.query.newstuff.QueryProgramResource.*;
import static org.lwjgl.opengl.GL30.*;
import static org.lwjgl.opengl.GL42.*;
import static org.lwjgl.opengl.GL43.*;

/*
    References: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetProgramInterface.xhtml
 */
@Getter
public enum QueryProgramInterface implements IQueryProgramInterface {
    UNIFORM(GL_UNIFORM, NAME_LENGTH, TYPE, ARRAY_SIZE, OFFSET, BLOCK_INDEX, ARRAY_STRIDE, MATRIX_STRIDE, IS_ROW_MAJOR, ATOMIC_COUNTER_BUFFER_INDEX, REFERENCED_BY_VERTEX_SHADER, REFERENCED_BY_TESS_CONTROL_SHADER, REFERENCED_BY_TESS_EVALUATION_SHADER, REFERENCED_BY_GEOMETRY_SHADER, REFERENCED_BY_FRAGMENT_SHADER, REFERENCED_BY_COMPUTE_SHADER, LOCATION),
    UNIFORM_BLOCK(GL_UNIFORM_BLOCK, NAME_LENGTH, BUFFER_BINDING, BUFFER_DATA_SIZE, NUM_ACTIVE_VARIABLES, ACTIVE_VARIABLES, REFERENCED_BY_VERTEX_SHADER, REFERENCED_BY_TESS_CONTROL_SHADER, REFERENCED_BY_TESS_EVALUATION_SHADER, REFERENCED_BY_GEOMETRY_SHADER, REFERENCED_BY_FRAGMENT_SHADER, REFERENCED_BY_COMPUTE_SHADER),
    ATOMIC_COUNTER_BUFFER(GL_ATOMIC_COUNTER_BUFFER, BUFFER_BINDING, BUFFER_DATA_SIZE, NUM_ACTIVE_VARIABLES, ACTIVE_VARIABLES),
    PROGRAM_INPUT(GL_PROGRAM_INPUT, NAME_LENGTH, TYPE, ARRAY_SIZE, REFERENCED_BY_VERTEX_SHADER, REFERENCED_BY_TESS_CONTROL_SHADER, REFERENCED_BY_TESS_EVALUATION_SHADER, REFERENCED_BY_GEOMETRY_SHADER, REFERENCED_BY_FRAGMENT_SHADER, REFERENCED_BY_COMPUTE_SHADER, LOCATION, IS_PER_PATCH, LOCATION_COMPONENT),
    PROGRAM_OUTPUT(GL_PROGRAM_OUTPUT, NAME_LENGTH, TYPE, ARRAY_SIZE, REFERENCED_BY_VERTEX_SHADER, REFERENCED_BY_TESS_CONTROL_SHADER, REFERENCED_BY_TESS_EVALUATION_SHADER, REFERENCED_BY_GEOMETRY_SHADER, REFERENCED_BY_FRAGMENT_SHADER, REFERENCED_BY_COMPUTE_SHADER, LOCATION, LOCATION_INDEX, IS_PER_PATCH, LOCATION_COMPONENT),
    VERTEX_SUBROUTINE(GL_VERTEX_SUBROUTINE, NAME_LENGTH),
    TESS_CONTROL_SUBROUTINE(GL_TESS_CONTROL_SUBROUTINE, NAME_LENGTH),
    TESS_EVALUATION_SUBROUTINE(GL_TESS_EVALUATION_SUBROUTINE, NAME_LENGTH),
    GEOMETRY_SUBROUTINE(GL_GEOMETRY_SUBROUTINE, NAME_LENGTH),
    FRAGMENT_SUBROUTINE(GL_FRAGMENT_SUBROUTINE, NAME_LENGTH),
    COMPUTE_SUBROUTINE(GL_COMPUTE_SUBROUTINE, NAME_LENGTH),
    VERTEX_SUBROUTINE_UNIFORM(GL_VERTEX_SUBROUTINE_UNIFORM, NAME_LENGTH, ARRAY_SIZE, NUM_COMPATIBLE_SUBROUTINES, COMPATIBLE_SUBROUTINES, LOCATION),
    TESS_CONTROL_SUBROUTINE_UNIFORM(GL_TESS_CONTROL_SUBROUTINE_UNIFORM, NAME_LENGTH, ARRAY_SIZE, NUM_COMPATIBLE_SUBROUTINES, COMPATIBLE_SUBROUTINES, LOCATION),
    TESS_EVALUATION_SUBROUTINE_UNIFORM(GL_TESS_EVALUATION_SUBROUTINE_UNIFORM, NAME_LENGTH, ARRAY_SIZE, NUM_COMPATIBLE_SUBROUTINES, COMPATIBLE_SUBROUTINES, LOCATION),
    GEOMETRY_SUBROUTINE_UNIFORM(GL_GEOMETRY_SUBROUTINE_UNIFORM, NAME_LENGTH, ARRAY_SIZE, NUM_COMPATIBLE_SUBROUTINES, COMPATIBLE_SUBROUTINES, LOCATION),
    FRAGMENT_SUBROUTINE_UNIFORM(GL_FRAGMENT_SUBROUTINE_UNIFORM, NAME_LENGTH, ARRAY_SIZE, NUM_COMPATIBLE_SUBROUTINES, COMPATIBLE_SUBROUTINES, LOCATION),
    COMPUTE_SUBROUTINE_UNIFORM(GL_COMPUTE_SUBROUTINE_UNIFORM, NAME_LENGTH, ARRAY_SIZE, NUM_COMPATIBLE_SUBROUTINES, COMPATIBLE_SUBROUTINES, LOCATION),
    TRANSFORM_FEEDBACK_VARYING(GL_TRANSFORM_FEEDBACK_VARYING, NAME_LENGTH, TYPE, ARRAY_SIZE, OFFSET, TRANSFORM_FEEDBACK_BUFFER_INDEX),
    BUFFER_VARIABLE(GL_BUFFER_VARIABLE, NAME_LENGTH, TYPE, ARRAY_SIZE, OFFSET, BLOCK_INDEX, ARRAY_STRIDE, MATRIX_STRIDE, IS_ROW_MAJOR, REFERENCED_BY_VERTEX_SHADER, REFERENCED_BY_TESS_CONTROL_SHADER, REFERENCED_BY_TESS_EVALUATION_SHADER, REFERENCED_BY_GEOMETRY_SHADER, REFERENCED_BY_FRAGMENT_SHADER, REFERENCED_BY_COMPUTE_SHADER, TOP_LEVEL_ARRAY_SIZE, TOP_LEVEL_ARRAY_STRIDE),
    SHADER_STORAGE_BLOCK(GL_SHADER_STORAGE_BLOCK, NAME_LENGTH, BUFFER_BINDING, BUFFER_DATA_SIZE, NUM_ACTIVE_VARIABLES, ACTIVE_VARIABLES, REFERENCED_BY_VERTEX_SHADER, REFERENCED_BY_TESS_CONTROL_SHADER, REFERENCED_BY_TESS_EVALUATION_SHADER, REFERENCED_BY_GEOMETRY_SHADER, REFERENCED_BY_FRAGMENT_SHADER, REFERENCED_BY_COMPUTE_SHADER),
    TRANSFORM_FEEDBACK_BUFFER(GL_TRANSFORM_FEEDBACK_BUFFER, BUFFER_BINDING, NUM_ACTIVE_VARIABLES, ACTIVE_VARIABLES, TRANSFORM_FEEDBACK_BUFFER_STRIDE);

    // Included in the glGetProgramResource table but not present in the glGetProgramInterface
    //ATOMIC_COUNTER_SHADER(REFERENCED_BY_VERTEX_SHADER, REFERENCED_BY_TESS_CONTROL_SHADER, REFERENCED_BY_TESS_EVALUATION_SHADER, REFERENCED_BY_GEOMETRY_SHADER, REFERENCED_BY_FRAGMENT_SHADER, REFERENCED_BY_COMPUTE_SHADER),
    //BUFFER(REFERENCED_BY_VERTEX_SHADER, REFERENCED_BY_TESS_CONTROL_SHADER, REFERENCED_BY_TESS_EVALUATION_SHADER, REFERENCED_BY_GEOMETRY_SHADER, REFERENCED_BY_FRAGMENT_SHADER, REFERENCED_BY_COMPUTE_SHADER),
    private final int interfaceType;
    private final List<IQueryProgramResource> resources;
    private final IntBuffer properties;

    QueryProgramInterface(int interfaceType, IQueryProgramResource... resources) {
        this.interfaceType = interfaceType;
        if (resources.length < 1)
            throw new IllegalArgumentException("Argument resources can't be less than one.");

        this.resources = Collections.unmodifiableList(Arrays.asList(resources));
        properties = MemUtils.newBufferFromValue(this.resources.stream()
                        .mapToInt(IQueryProgramResource::programResourceType).toArray())
                .asReadOnlyBuffer();
    }
}
